apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server
  namespace: express-server
  labels:
    app: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
      - name: express-server
        image: express-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
      restartPolicy: Always
