apiVersion: apps/v1
kind: Deployment
metadata:
  name: gws-playground-api
  labels:
    app: gws-playground-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gws-playground-api
  template:
    metadata:
      labels:
        app: gws-playground-api
    spec:
      containers:
      - name: gws-playground-api
        image: gws-playground-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: "mysql://gws_user:devpassword@mysql:3306/gws_playground_db"
        - name: ENVIRONMENT
          value: "development"
      restartPolicy: Always
