apiVersion: v1
kind: Service
metadata:
  name: gws-playground-api
  labels:
    app: gws-playground-api
spec:
  type: ClusterIP
  selector:
    app: gws-playground-api
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
